apiVersion: v1
kind: Service
metadata:
  labels:
    app: jentrata-msh
  name: jentrata-msh
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jentrata-msh
  sessionAffinity: None
  type: ClusterIP